baseURL = "https://vishwashah.me/"
languageCode = "en-us"
title = "Vishwa Shah"
googleAnalytics = "UA-57527171-3"
copyright = "© 2020"

# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Add your Disqus shortname here.
# disqusShortname = ""

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/vishifishy"
  github = "https://github.com/vishwa35"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/postcardsfromvish"
  linkedin = "https://www.linkedin.com/in/vishwa35/"
  medium = "https://medium.com/@vishwa35"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Instagram", "LinkedIn", "Medium"]

  # Metadata for Twitter cards, defaults to params.twitter
  twitterSite = "@vishifishy"
  twitterAuthor = "@vishifishy"

  keywords = ['vishwa', 'shah', 'tampa', 'atlanta', 'georgia tech', 'technology', 'software', 'blog', 'postcardsfromvish', 'awhsiv', 'vishwa35', 'vishifishy', 'hillsborough', 'lyft', 'palantir', 'square', 'redfin', 'computer science', 'photography', 'podcast', 'aneka', 'yja', 'gatech']

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "resume"
  name = "resume"
  title = "Resume"
  url = "/resume"

[[menu.main]]
  identifier = "portfolio"
  name = "portfolio"
  title = "Portfolio"
  url = "/portfolio"

[[menu.main]]
  identifier = "ongoing projects"
  name = "ongoing projects"
  title = "Ongoing Projects"
  url = "/ongoing-projects"

[[menu.main]]
  identifier = "reading list"
  name = "reading list"
  title = "Reading List"
  url = "/reading-list"

[taxonomies]
  category = "categories"
  tag = "tags"
  projTags = "projtags"
